services:
  nh-personal-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nh-personal-app
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - nh-personal-network

networks:
  nh-personal-network:
    driver: bridge 