version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: personal_trainer_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=personal-db.cbkc0cg2c7in.us-east-2.rds.amazonaws.com
      - DB_PORT=3306
      - DB_USERNAME=admin
      - DB_PASSWORD=Rdms95gn!
      - DB_NAME=personal_trainer_db
      - JWT_SECRET=nh-personal-jwt-secret-2024
      - BCRYPT_SALT_ROUNDS=12
      - LOG_LEVEL=info
    networks:
      - personal_trainer_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 120s
    volumes:
      - /var/log/nh-personal:/opt/nh-personal/logs

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: personal_trainer_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - personal_trainer_network
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
      - NODE_ENV=production

networks:
  personal_trainer_network:
    driver: bridge 