services:
  nh-personal-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nh-personal-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=mysql://admin:Rdms95gn!@personal-db.cbkc0cg2c7in.us-east-2.rds.amazonaws.com:3306/personal_trainer_db
      - JWT_ACCESS_TOKEN_SECRET=nh-personal-access-token-secret-2024
      - JWT_REFRESH_TOKEN_SECRET=nh-personal-refresh-token-secret-2024
      - ENCRYPTION_KEY=nh-personal-encryption-key-2024
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - nh-personal-network

networks:
  nh-personal-network:
    driver: bridge 